// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ZivaRT
{
  internal enum ActiveTransformParts : sbyte
  {
    FullTransform = 0,
    IgnoreTranslationAndScale = 1,
  };
}
