// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ZivaRT
{

internal enum CorrectiveType : sbyte
{
  TensorSkin = 0,
  EigenSkin = 1,
  FullSpace = 2,
};


}
