// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ZivaRT
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

internal struct MatrixXi16 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static MatrixXi16 GetRootAsMatrixXi16(ByteBuffer _bb) { return GetRootAsMatrixXi16(_bb, new MatrixXi16()); }
  public static MatrixXi16 GetRootAsMatrixXi16(ByteBuffer _bb, MatrixXi16 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public MatrixXi16 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(__p.__vector(o) + j * 2) : (short)0; }
  public int XLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<short> GetXBytes() { return __p.__vector_as_span<short>(4, 2); }
#else
  public ArraySegment<byte>? GetXBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public short[] GetXArray() { return __p.__vector_as_array<short>(4); }
  public int Rows { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Cols { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<ZivaRT.MatrixXi16> CreateMatrixXi16(FlatBufferBuilder builder,
      VectorOffset xOffset = default(VectorOffset),
      int rows = 0,
      int cols = 0) {
    builder.StartTable(3);
    MatrixXi16.AddCols(builder, cols);
    MatrixXi16.AddRows(builder, rows);
    MatrixXi16.AddX(builder, xOffset);
    return MatrixXi16.EndMatrixXi16(builder);
  }

  public static void StartMatrixXi16(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddX(FlatBufferBuilder builder, VectorOffset xOffset) { builder.AddOffset(0, xOffset.Value, 0); }
  public static VectorOffset CreateXVector(FlatBufferBuilder builder, short[] data) { builder.StartVector(2, data.Length, 2); for (int i = data.Length - 1; i >= 0; i--) builder.AddShort(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateXVectorBlock(FlatBufferBuilder builder, short[] data) { builder.StartVector(2, data.Length, 2); builder.Add(data); return builder.EndVector(); }
  public static void StartXVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(2, numElems, 2); }
  public static void AddRows(FlatBufferBuilder builder, int rows) { builder.AddInt(1, rows, 0); }
  public static void AddCols(FlatBufferBuilder builder, int cols) { builder.AddInt(2, cols, 0); }
  public static Offset<ZivaRT.MatrixXi16> EndMatrixXi16(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ZivaRT.MatrixXi16>(o);
  }
};


}
